services:
  question:
    build: ./backend/question-service
    ports:
      - "3002:3002"
  
  user:
    build: ./backend/user-service
    ports:
      - "3001:3001"
  
  code-execution-rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "7000:5672"
  
  code-execution-redis:
    image: redis:alpine
    ports:
      - "7001:6379"
  
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/nginx/.env
    ports:
      - "80:80"
