services:
  question:
    build: ./backend/question-service
    ports:
      - "3002:3002"

  user:
    build: ./backend/user-service
    ports:
      - "3001:3001"
  
  code-execution-rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "7000:5672"
  
  code-execution-redis:
    image: redis:alpine
    ports:
      - "7001:6379"
  
  code-execution-server:
    build: ./backend/code-execution-service/server
    ports:
      - "7002:7002"
    depends_on:
      - code-execution-rabbitmq
      - code-execution-redis
  
  code-execution-worker:
    build: ./backend/code-execution-service/worker
    pids_limit: 60
    cpus: 1
    mem_limit: 150M
    depends_on:
      - code-execution-rabbitmq
      - code-execution-redis
    deploy:
      replicas: 4
      restart_policy:
        condition: any
        delay: 3s
        window: 5s
  
  rabbitmq:
    image: dedsecrattle/rabbitmq-delayed-exchange
    ports:
      - "5672:5672" # RabbitMQ message broker
      - "15672:15672" # RabbitMQ management plugin
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  matching:
    build: ./backend/matching-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: "file:./dev.db"
      RABBITMQ_URL: "amqp://rabbitmq:5672"

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/nginx/.env
    ports:
      - "80:80"
    depends_on:
      - user
      - matching
      - question
      - rabbitmq
