services:
  question:
    build: ./backend/question-service
    ports:
      - "3002:3002"
    restart: on-failure

  user:
    build: ./backend/user-service
    ports:
      - "3001:3001"
    restart: on-failure

  code-execution-rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - "7004:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  code-execution-redis:
    image: redis:alpine
    ports:
      - "7001:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  code-execution-server:
    build: ./backend/code-execution-service/server
    ports:
      - "7002:7002"
    depends_on:
      code-execution-rabbitmq:
        condition: service_healthy
      code-execution-redis:
        condition: service_healthy

  code-execution-worker:
    build: ./backend/code-execution-service/worker
    pids_limit: 60
    cpus: 1
    mem_limit: 150M
    depends_on:
      code-execution-rabbitmq:
        condition: service_healthy
      code-execution-redis:
        condition: service_healthy
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 3s
        window: 5s

  rabbitmq:
    image: dedsecrattle/rabbitmq-delayed-exchange
    ports:
      - "5672:5672" # RabbitMQ message broker
      - "15672:15672" # RabbitMQ management plugin
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  communication:
    build: ./backend/communication-service
    ports:
      - "3004:3004"
      - "9000:9000"

  matching:
    build: ./backend/matching-service
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3003:3003"

  collaboration:
    build: ./backend/collaboration-service
    ports:
      - "3005:3005"

  frontend:
    build: ./frontend
    environment:
      - QUESTION_SERVICE_URL=http://question:3002
      - USER_SERVICE_URL=http://user:3001/
    ports:
      - "80:80"
    depends_on:
      - user
      - matching
      - question
      - collaboration
      - rabbitmq
